my_lakehouse:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_PROJECT_DIR') }}/local_db.duckdb"
      extensions:
        - parquet
      threads: 4

    prod:
      type: duckdb
      path: "{{ env_var('DBT_PROJECT_DIR') }}/local_db.duckdb"
      threads: 4

  target: dev
